DROP EXTENSION pgcrypto CASCADE;

DROP TABLE Users CASCADE;
DROP TABLE Languages CASCADE;
DROP TABLE GradeLevel CASCADE;
DROP TABLE Students CASCADE;
DROP TABLE Teachers CASCADE;
DROP TABLE TeacherAvailability CASCADE;
DROP TABLE Category CASCADE;
DROP TABLE Worksheets CASCADE;
DROP TABLE Submitted CASCADE;
DROP TABLE SubmissionModifyDate CASCADE;
DROP TABLE Returned CASCADE;

DROP FUNCTION create_user CASCADE;
DROP FUNCTION create_worksheet CASCADE;
